from typing import List, Optional, TypedDict
from pydantic import BaseModel, Field, field_validator


class ContractTerms(BaseModel):
    """Structured contract terms extracted from raw contract text by the Planner agent."""

    party_a: str = Field(description="Primary disclosing/service providing party")
    party_b: str = Field(description="Client or receiving party")
    effective_date: str = Field(description="Contract start date or effective date")
    initial_price: float = Field(
        description="Initial contract value or total price in USD"
    )
    payment_terms: str = Field(
        description="Payment schedule or terms (e.g. Net 30, upfront)"
    )
    renewal_terms: str = Field(
        description="Auto-renewal clause or renewal condition"
    )
    key_clauses: List[str] = Field(
        default_factory=list, description="Key obligations, penalties, or SLA terms"
    )

    @field_validator("initial_price", mode="before")
    @classmethod
    def coerce_initial_price(cls, v):
        if v is None or v == "":
            return 0.0
        if isinstance(v, str):
            cleaned = "".join(c for c in v if c.isdigit() or c in ".-")
            return float(cleaned) if cleaned else 0.0
        return float(v)


class CounterOffer(BaseModel):
    """Structured counter-offer generated by the Drafter agent."""

    proposed_price: float = Field(
        description="Proposed renegotiated price in USD"
    )
    discount_percentage: float = Field(
        description="Calculated discount percentage relative to initial price"
    )
    revised_payment_terms: str = Field(
        description="Proposed revised payment terms (e.g. Net 60)"
    )
    revised_clauses: List[str] = Field(
        default_factory=list, description="Proposed modifications to contractual clauses"
    )
    rationale: str = Field(
        description="Business rationale supporting the proposed counter-offer"
    )

    @field_validator("proposed_price", "discount_percentage", mode="before")
    @classmethod
    def coerce_counter_offer_floats(cls, v):
        if v is None or v == "":
            return 0.0
        if isinstance(v, str):
            cleaned = "".join(c for c in v if c.isdigit() or c in ".-")
            return float(cleaned) if cleaned else 0.0
        return float(v)


class WorkflowState(TypedDict, total=False):
    """State dictionary passed between LangGraph nodes."""

    raw_text: str
    contract_terms: Optional[ContractTerms]
    counter_offer: Optional[CounterOffer]
    math_valid: bool
    reviewer_feedback: Optional[str]
    math_retry_count: int
    human_approved: Optional[bool]
    final_email_status: Optional[str]
    error: Optional[str]
